name: EpicCore
version: '${version}'
main: gg.minecrush.epiccore.EpicCore
api-version: '1.20'
authors:
  - snowy
  - awel
  - jayden
  - eric
website: https://store.minecrush.gg
commands:
  spawn:
    description: Teleport yourself or others to spawn
  setspawn:
    description: Set the spawn location for the server.
  report:
    description: Report other players for violations if the second argument is not fulfilled a gui with options will be shown.
  discord:
    description: Use this command to join the discord server
  clearchat:
    description: Use this command to clear chat if there has been spam or any blacklisted words option for the first argument is how many blank lines to send
    aliases: cc
  epiccore:
    description: Admin command to view the configuration for EpicCore
    aliases: epicadmin
    usage: epiccore
  mutechat:
    description: Mute server chat.
    aliases: chatmute
  broadcast:
    aliases: bc
    description: Broadcast messages to all online players!
  gmc:
    description: Gamemode creative command
  gma:
    description: Gamemode adventure command
  gmsp:
    description: Gamemode spectator command
  gms:
    description: Gamemode survival command
  gamemode:
    aliases: gm
    description: Update your gamemode
  fly:
    aliases: flight
    description: Toggle yours or another player's flight mode.
  flyspeed:
    description: Update a players movement speed
    aliases: walkspeed
  invsee:
    description: View a players inventory
    aliases: inventorysee
  enderchest:
    description: View a players enderchest
    aliases: ec
  heal:
    description: Heal yourself or heal a player
  feed:
    description: Feed yourself or another person
    aliases: stuff
  warps:
    description: Manage, teleport and list warps!
    aliases: warp