name: EpicCore
version: '${version}'
main: gg.minecrush.epiccore.EpicCore
api-version: '1.20'
authors:
  - snowy
  - awel
  - jayden
website: https://snowyjs.lol
commands:
  spawn:
    description: Teleport yourself or others to spawn
    usage: spawn [target]
  setspawn:
    description: Set the spawn location for the server.
  report:
    description: Report other players for violations if the second argument is not fulfilled a gui with options will be shown.
    usage: report <target> [reason]
  discord:
    description: Use this command to join the discord server
  clearchat:
    description: Use this command to clear chat if there has been spam or any blacklisted words option for the first argument is how many blank lines to send
    aliases: cc
    usage: clearchat [integer]
  epiccore:
    description: Admin command to view the configuration for EpicCore
    aliases: epicadmin
    usage: epiccore
  mutechat:
    description: Admin mutechat command
    aliases: chatmute
  broadcast:
    description: Broadcast messages to all online players!
  gmc:
    description: Gamemode creative command
  gma:
    description: Gamemode adventure command
  gmsp:
    description: Gamemode spectator command
  gms:
    description: Gamemode survival command
  gamemode:
    description: Update your gamemode
  fly:
    usage: fly [player]
    aliases: flight
    description: Toggle yours or another player's flight mode.